#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$SCRIPT_DIR"
ENV_FILE="$HOME/.autoware_env.sh"
CYCLONE_FILE="$HOME/cyclonedds.xml"
SYSCTL_FILE="/etc/sysctl.d/60-autoware-cyclonedds.conf"

ROS_DOMAIN_ID_VALUE="${ROS_DOMAIN_ID_VALUE:-26}"
DDS_INTERFACE="${DDS_INTERFACE:-lo}"
PERSIST_BASHRC=1
ENABLE_JETSON_CLOCKS=0
DRY_RUN=0

log() {
  printf '[prepare] %s\n' "$*"
}

warn() {
  printf '[prepare][warn] %s\n' "$*" >&2
}

run_cmd() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] %s\n' "$*"
  else
    eval "$@"
  fi
}

is_sourced() {
  [[ "${BASH_SOURCE[0]}" != "$0" ]]
}

usage() {
  cat <<'EOF'
Usage:
  bash prepare.sh [options]
  source prepare.sh [options]

Options:
  --iface <name>              DDS interface name. Default: lo
  --iface auto                Use autodetermine="true" in cyclonedds.xml
  --ros-domain-id <id>        ROS_DOMAIN_ID value. Default: 26
  --enable-jetson-clocks      Run jetson_clocks if available
  --no-bashrc                 Do not append source line to ~/.bashrc
  --dry-run                   Print actions without changing the system
  -h, --help                  Show this help

Examples:
  bash prepare.sh
  bash prepare.sh --iface auto
  source prepare.sh --iface lo --ros-domain-id 26

Notes:
  - This script writes:
      * /etc/sysctl.d/60-autoware-cyclonedds.conf
      * ~/cyclonedds.xml
      * ~/.autoware_env.sh
  - If not sourced, shell exports will apply to new terminals via ~/.bashrc.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --iface)
      [[ $# -ge 2 ]] || { warn "--iface requires a value"; exit 1; }
      DDS_INTERFACE="$2"
      shift 2
      ;;
    --ros-domain-id)
      [[ $# -ge 2 ]] || { warn "--ros-domain-id requires a value"; exit 1; }
      ROS_DOMAIN_ID_VALUE="$2"
      shift 2
      ;;
    --enable-jetson-clocks)
      ENABLE_JETSON_CLOCKS=1
      shift
      ;;
    --no-bashrc)
      PERSIST_BASHRC=0
      shift
      ;;
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      warn "Unknown option: $1"
      usage
      exit 1
      ;;
  esac
done

write_sysctl_file() {
  log "Writing sysctl file: $SYSCTL_FILE"
  run_cmd "sudo tee '$SYSCTL_FILE' >/dev/null <<'EOF'
# Autoware / CycloneDDS recommended network tuning
net.core.rmem_max=2147483647
net.ipv4.ipfrag_time=3
net.ipv4.ipfrag_high_thresh=134217728
EOF"
}

apply_sysctl() {
  log "Applying sysctl settings"
  run_cmd "sudo sysctl -p '$SYSCTL_FILE' >/dev/null"
}

enable_lo_multicast() {
  log "Enabling multicast on lo"
  run_cmd "sudo ip link set lo multicast on"
}

write_cyclonedds_file() {
  log "Writing CycloneDDS config: $CYCLONE_FILE"

  local interfaces_block
  if [[ "$DDS_INTERFACE" == "auto" ]]; then
    interfaces_block='      <Interfaces>
        <NetworkInterface autodetermine="true" priority="default" multicast="default" />
      </Interfaces>'
  else
    interfaces_block="      <Interfaces>
        <NetworkInterface autodetermine=\"false\" name=\"$DDS_INTERFACE\" priority=\"default\" multicast=\"default\" />
      </Interfaces>"
  fi

  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] write %s with DDS interface %s\n' "$CYCLONE_FILE" "$DDS_INTERFACE"
    return
  fi

  cat > "$CYCLONE_FILE" <<EOF
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
  <Domain Id="any">
    <General>
$interfaces_block
      <AllowMulticast>default</AllowMulticast>
      <MaxMessageSize>65500B</MaxMessageSize>
    </General>
    <Discovery>
      <ParticipantIndex>none</ParticipantIndex>
    </Discovery>
    <Internal>
      <SocketReceiveBufferSize min="10MB"/>
      <Watermarks>
        <WhcHigh>500kB</WhcHigh>
      </Watermarks>
    </Internal>
  </Domain>
</CycloneDDS>
EOF
}

write_env_file() {
  log "Writing Autoware shell env file: $ENV_FILE"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] write %s with ROS_DOMAIN_ID=%s\n' "$ENV_FILE" "$ROS_DOMAIN_ID_VALUE"
    return
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by $WORKSPACE_DIR/prepare.sh
export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
export CYCLONEDDS_URI=file://$CYCLONE_FILE
export ROS_DOMAIN_ID=$ROS_DOMAIN_ID_VALUE
unset ROS_LOCALHOST_ONLY
EOF
}

ensure_bashrc_hook() {
  [[ "$PERSIST_BASHRC" -eq 1 ]] || return 0

  local source_line='[ -f "$HOME/.autoware_env.sh" ] && source "$HOME/.autoware_env.sh"'
  log "Ensuring ~/.bashrc sources $ENV_FILE"

  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '[dry-run] ensure ~/.bashrc contains source line for %s\n' "$ENV_FILE"
    return
  fi

  if ! grep -Fq "$HOME/.autoware_env.sh" "$HOME/.bashrc"; then
    {
      printf '\n# Autoware runtime environment\n'
      printf '%s\n' "$source_line"
    } >> "$HOME/.bashrc"
  fi
}

enable_jetson_clocks() {
  [[ "$ENABLE_JETSON_CLOCKS" -eq 1 ]] || return 0

  if command -v jetson_clocks >/dev/null 2>&1; then
    log "Enabling jetson_clocks"
    run_cmd "sudo jetson_clocks"
  else
    warn "jetson_clocks not found; skipping"
  fi
}

print_summary() {
  log "Summary"
  if [[ "$DRY_RUN" -eq 1 ]]; then
    printf '  workspace        : %s\n' "$WORKSPACE_DIR"
    printf '  ros_domain_id    : %s\n' "$ROS_DOMAIN_ID_VALUE"
    printf '  dds_interface    : %s\n' "$DDS_INTERFACE"
    printf '  bashrc_hook      : %s\n' "$PERSIST_BASHRC"
    printf '  jetson_clocks    : %s\n' "$ENABLE_JETSON_CLOCKS"
    return
  fi

  printf '  workspace        : %s\n' "$WORKSPACE_DIR"
  printf '  ros_domain_id    : %s\n' "$ROS_DOMAIN_ID_VALUE"
  printf '  dds_interface    : %s\n' "$DDS_INTERFACE"
  printf '  env_file         : %s\n' "$ENV_FILE"
  printf '  cyclone_file     : %s\n' "$CYCLONE_FILE"
  printf '  sysctl_file      : %s\n' "$SYSCTL_FILE"
  printf '  rmw              : %s\n' "$(grep '^export RMW_IMPLEMENTATION=' "$ENV_FILE" | cut -d= -f2-)"
  printf '  cyclone_uri      : %s\n' "$(grep '^export CYCLONEDDS_URI=' "$ENV_FILE" | cut -d= -f2-)"
  printf '  lo multicast     : %s\n' "$(ip link show lo | head -n 1)"
  printf '  sysctl rmem_max  : %s\n' "$(sysctl -n net.core.rmem_max)"
  printf '  sysctl ipfrag_t  : %s\n' "$(sysctl -n net.ipv4.ipfrag_time)"
  printf '  sysctl ipfrag_hi : %s\n' "$(sysctl -n net.ipv4.ipfrag_high_thresh)"
  printf '  timedatectl      : %s\n' "$(timedatectl show -p NTPSynchronized --value 2>/dev/null || true)"
}

source_env_if_possible() {
  if is_sourced; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      printf '[dry-run] source %s into current shell\n' "$ENV_FILE"
    else
      # shellcheck disable=SC1090
      source "$ENV_FILE"
      log "Current shell updated from $ENV_FILE"
    fi
  else
    log "Open a new terminal or run: source $ENV_FILE"
  fi
}

main() {
  write_sysctl_file
  apply_sysctl
  enable_lo_multicast
  write_cyclonedds_file
  write_env_file
  ensure_bashrc_hook
  enable_jetson_clocks
  print_summary
  source_env_if_possible
}

main
