approx_camera_info_publisher:
  ros__parameters:
    image_topic: /sensing/camera/front/image_raw
    camera_info_topic: /sensing/camera/front/camera_info
    frame_id_override: ""
    width_override: 0
    height_override: 0
    fx: 0.0
    fy: 0.0
    cx: 0.0
    cy: 0.0
    distortion_model: plumb_bob
    d: [0.0, 0.0, 0.0, 0.0, 0.0]
    r: []
    p: []
    hfov_deg: 0.0
    vfov_deg: 0.0
    dfov_deg: 110.0
