/**:
  ros__parameters:
    wheel_radius: 0.122
    wheel_width: 0.065
    wheel_base: 0.60
    wheel_tread: 0.52
    front_overhang: 0.12
    rear_overhang: 0.15
    left_overhang: 0.05
    right_overhang: 0.05
    vehicle_height: 0.60
    max_steer_angle: 0.70
